import {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  LayoutDashboard,
  Bell,
  Brain,
  Bug,
  Calendar,
  Check,
  CheckCircle2,
  ChevronRight,
  CirclePlus,
  Clapperboard,
  CloudUpload,
  Coins,
  CreditCard,
  Download,
  Film,
  Hourglass,
  Info,
  KeyRound,
  Loader2,
  Lock,
  Mail,
  MailCheck,
  MonitorPlay,
  Package,
  Play,
  PlayCircle,
  Plug,
  Rocket,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Store,
  Terminal,
  Upload,
  UserCircle,
  Trash2,
  Users,
  VideoOff,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Central registry — use these keys everywhere instead of Material icon names. */
export const APP_ICONS = {
  add_circle: CirclePlus,
  admin_panel_settings: ShieldCheck,
  analytics: BarChart3,
  api: Plug,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  bug_report: Bug,
  calendar_month: Calendar,
  insights: BarChart3,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: CloudUpload,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  download: Download,
  error: AlertCircle,
  face: UserCircle,
  group: Users,
  hourglass_top: Hourglass,
  info: Info,
  lock_reset: KeyRound,
  mail: Mail,
  mark_email_read: MailCheck,
  movie: Film,
  movie_edit: Clapperboard,
  neurology: Brain,
  notifications: Bell,
  package_2: Package,
  payments: CreditCard,
  password: Lock,
  person: UserCircle,
  delete: Trash2,
  play_arrow: Play,
  play_circle: PlayCircle,
  progress_activity: Loader2,
  rocket_launch: Rocket,
  search: Search,
  settings: Settings,
  shield: Shield,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  smart_display: MonitorPlay,
  storefront: Store,
  terminal: Terminal,
  today: Calendar,
  toll: Coins,
  upload: Upload,
  verified_user: ShieldCheck,
  video_library: Clapperboard,
  videocam_off: VideoOff,
  bolt: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof APP_ICONS;

/** Dashboard sidebar nav */
export const DASHBOARD_NAV_ICONS = {
  "/dashboard": "dashboard",
  "/dashboard/videos": "video_library",
  "/dashboard/create": "add_circle",
  "/dashboard/billing": "credit_card",
} as const;

/** Admin sidebar — dashboard key uses LayoutDashboard; map uses BarChart3 for overview */
export const ADMIN_NAV_ICONS: Record<string, IconName> = {
  "/admin/dashboard": "dashboard",
  "/admin/users": "group",
  "/admin/videos": "video_library",
  "/admin/analytics": "analytics",
  "/admin/api-logs": "terminal",
};
